name: Release

on:
  release:
    types:
      - released
  workflow_dispatch:

jobs:
  release-to-pypi:
    name: Release on PyPI server
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Build dist
        run: |
            python3 setup.py sdist
      - name: Upload to PyPI
        run: |
            pip3 install twine==5.1.1
            export TWINE_USERNAME=__token__
            export TWINE_PASSWORD="${{ secrets.PYPI_API_TOKEN }}"
            twine upload --verbose dist/*
